read -d \\ CONFIGURE_OPTIONS <<HERE
--disable-hdri
--disable-opencl
--disable-openmp
--without-magick-plus-plus
--without-modules
--with-quantum-depth=8
--with-jpeg
--with-lcms2
--with-png
--with-tiff
--with-webp
--with-zlib
--without-autotrace
--without-bzlib
--without-dps
--without-djvu
--without-fftw
--without-fpx
--without-fontconfig
--without-freetype
--without-gslib
--without-gvc
--without-jbig
--without-jp2
--without-lcms
--without-lqr
--without-lzma
--without-openexr
--without-pango
--without-perl
--without-rsvg
--without-wmf
--without-x
--without-xml
\\
HERE
CONFIGURE_OPTIONS="$(echo $CONFIGURE_OPTIONS)"
